default:
  numbers:
    timer: 45 
    extra_timer: 0 
  letters:
    timer: 30 
    extra_timer: 0

family:
  numbers:
    timer: 45
    extra_timer: 30  # additional time for grandmother
  letters:
    timer: 30 
    extra_timer: 0